### PR TITLE
fixes #9656 - output hour, minute, second to content-host-trend

### PR DESCRIPTION
**Pull request by thomasmckay**
```
$ hammer content-report content-host-trend --organization-label megacorp --content-host-id aceb31b3-280e-4a43-b744-b8d9fc056a51
Task 38e99cae-6dd1-4dfd-8ac6-2ac35586d97f: success
Date,Status
2015-03-05 13:07:13,valid
2015-03-05 13:26:02,invalid
```

### CODE REVIEW

**Comment by komidore64** [comment]
ack

**Comment by komidore64** [comment]
if you're wanting to show HMS, then you should also be able to filter by the same granularity. except at this time, i'm pretty sure gutterball only accepts `YYYY-MM-DD`.

NACK

**Comment by thomasmckay** [comment]
@komidore64 https://bugzilla.redhat.com/show_bug.cgi?id=1199181

**Comment by komidore64** [comment]
ok. i'm okay with this change once that RFE has made it into gutterball.

**Comment by thomasmckay** [comment]
@komidore64  I'd prefer this go in sooner as the current report output would look like this for a guest:
```
2015-03-05,invalid
2015-03-05,partial
2015-03-05,partial
2015-03-05,valid
```
By including the hms the user could tune their virt-who checkin effectively to reduce the time spent in the yellow phase for a system.

**Comment by komidore64** [comment]
ok

ACK

**Pull request merged**
